[project]
name = "brain"
version = "0.1.0"
description = "Serqet brain"
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.129.0",
    "langchain-openai>=1.1.9",
    "langgraph>=1.0.8",
    "uvicorn>=0.41.0",
]
